---

- name: Install basic packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
     - vim
     - aptitude


- debug:
    msg: " version -  {{ item }}"
  with_items:
     - "{{ java_version }}"
     - "{{ dotnet_version }}"
  